<a href="https://colab.research.google.com/github/Rithanya77-05/rithanya-codebooster-2026/blob/main/Day-3/Day-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests --quiet  #pip-package information python(playstore in our mobile)--addon application
import pandas as pd
import numpy as np
import requests # to communicaate with the apis or websites we need it
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [10]:
raw_df=pd.read_csv('/content/messy_sales_data.csv')
print(f"Raw data loaded:  {raw_df.shape[0]} rows,{raw_df.shape[1]} columns")
print(f"columns in the dataset :{raw_df.columns.tolist()}")
print("First 5 rows")
print(raw_df.head().to_string(index=False))

Raw data loaded:  30 rows,9 columns
columns in the dataset :['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']
First 5 rows
 order_id customer_name  product    category  quantity  unit_price order_date      city   sales_rep
     1001  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma
     1002    Priya Nair      NaN Electronics       1.0       15000 2024-01-07     Delhi  Sunita Rao
     1003    AMIT VERMA Keyboard Accessories       3.0        1200 2024-01-08 Bangalore Anil Sharma
     1004  Sunita Patel  Monitor Electronics       NaN       22000 2024-01-10   Chennai  Ravi Kumar
     1005  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma

In [17]:
print('\n MISSING VALUES per column:')
print(raw_df.isnull().sum())
print(f"\n DuPLICATE ROWS: {raw_df.duplicated().sum()}")
print('\n Data types of each column:')
print(raw_df.dtypes)
print(f"Unique categories: {raw_df['category'].unique()} ")
print(f" Sample customer nmaes:", raw_df['customer_name'].dropna().unique()[:8]) #dropna it will remove the null value and disply from the next
print(" sample oder_date", raw_df['order_date'].unique()[:6])

 MISSING VALUES per column:
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

 DuPLICATE ROWS: 0

 Data types of each column:
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object
Unique categories: ['Electronics' 'Accessories' nan]
 Sample customer nmaes: ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']
 sample oder_date ['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12']

In [18]:
df=raw_df.copy() #gonna work in this copy datset only
print(f"Working copy created:{df.shape}")
print('Raw_df is untouched - we can always reet by running df= raw_df.copy()')

Working copy created:(30, 9)
Raw_df is untouched - we can always reet by running df= raw_df.copy()

In [29]:
print('Before fixing nulls:', df.isnull().sum().sum(),'total missing values') #total missing values it will give for second .sum()
df['customer_name'].fillna('Unknown Customer', inplace=True) # fillna() meaning it will replace the null customer with unkown customer
median_qty=df['quantity'].median() #take the median value
df['quantity'].fillna(median_qty, inplace=True)
print(f"Filled misssing quantity with median: {median_qty}")
df['category'].fillna("Uncategorized",inplace=True)
print("After fixing values:", df.isnull().sum().sum(), 'Total missing values')
print(df.head().to_string(index=False))
df['product'].isnull().sum()
df['product'].fillna('Mysteeerious product',inplace=True)
df.head()
#df['product'].fillna()

Before fixing nulls: 0 total missing values
Filled misssing quantity with median: 2.0
After fixing values: 0 Total missing values
 order_id customer_name              product    category  quantity  unit_price order_date      city   sales_rep
     1001  Ramesh Kumar               Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma
     1002    Priya Nair Mysteeerious product Electronics       1.0       15000 2024-01-07     Delhi  Sunita Rao
     1003    AMIT VERMA             Keyboard Accessories       3.0        1200 2024-01-08 Bangalore Anil Sharma
     1004  Sunita Patel              Monitor Electronics       2.0       22000 2024-01-10   Chennai  Ravi Kumar
     1005  Ramesh Kumar               Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,Mysteeerious product,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [25]:
## REmoving duplicates
print(f'Be4 duplicate: {len(df)} rows')
print(f'duplicate rows: {df.duplicated().sum()}')
print("\n duplicate rows:")
print(df[df.duplicated(keep=False)][['order_id', 'customer_name','product']]) ## keep=False
df.drop_duplicates(inplace=True) ## in raw_df alsoo we are going to store it,, not only in df

print(f'\nAfter duplication: {len(df)} rows')
print(f'Rows removed: {len(raw_df)-len(df)}')

Be4 duplicate: 30 rows
duplicate rows: 0

 duplicate rows:
Empty DataFrame
Columns: [order_id, customer_name, product]
Index: []

After duplication: 30 rows
Rows removed: 0

In [48]:
print('sample dates before parsing')
print(df['order_date'].head(8))
df['order_date']= pd.to_datetime(
    df['order_date'],
    dayfirst=False,  #no need of day first
    errors='coerce' # it will fix itself and then display
)

nat_count = df['order_date'].isnull().sum()
print(f"\n Unparaseable dates(NaT): {nat_count}") #not a time nat

df['year'] = df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']= df['order_date'].dt.strftime('%B')
df['day_name']=df['order_date'].dt.strftime('%A')

print('\n Sample dates after paring:')
print(df[['order_date','year','month','month_name','day_name']].head(5))

sample dates before parsing
0   2024-01-05
1   2024-01-07
2   2024-01-08
3   2024-01-10
4   2024-01-05
5          NaT
6   2024-01-12
7   2024-01-13
Name: order_date, dtype: datetime64[ns]

 Unparaseable dates(NaT): 2

 Sample dates after paring:
  order_date    year  month month_name   day_name
0 2024-01-05  2024.0    1.0    January     Friday
1 2024-01-07  2024.0    1.0    January     Sunday
2 2024-01-08  2024.0    1.0    January     Monday
3 2024-01-10  2024.0    1.0    January  Wednesday
4 2024-01-05  2024.0    1.0    January     Friday

In [57]:
print(f"Before standardization: {df['customer_name'].tolist()[:5]}" ) #tolist () and unique() are also displaying in list format
df['customer_name']=(
    df['customer_name']
    .str.title()
    .str.strip()
)
print(f"After standartization: {df['customer_name'].tolist()[:5]}")

Before standardization: ['Ramesh Kumar', 'Priya Nair', 'AMIT VERMA', 'Sunita Patel', 'Ramesh Kumar']
After standartization: ['Ramesh Kumar', 'Priya Nair', 'Amit Verma', 'Sunita Patel', 'Ramesh Kumar']

In [62]:
print('Revenue Column created:')
df['revenue']= df['quantity']*df['unit_price']
print(df[ ['customer_name','quantity','unit_price','revenue']].head(10))
print("Total revenue",df['revenue'].sum())

Revenue Column created:
      customer_name  quantity  unit_price  revenue
0      Ramesh Kumar       2.0       45000  90000.0
1        Priya Nair       1.0       15000  15000.0
2        Amit Verma       3.0        1200   3600.0
3      Sunita Patel       2.0       22000  44000.0
4      Ramesh Kumar       2.0       45000  90000.0
5       Kiran Mehta      10.0         800   8000.0
6      Deepak Singh       2.0        3500   7000.0
7  Unknown Customer       1.0        2500   2500.0
8        Ananya Das       1.0       45000  45000.0
9       Vikram Iyer       5.0        1200   6000.0
Total revenue 818000.0

In [72]:
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce').astype(int)
df.head(30)

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep,year,month,month_name,day_name,revenue
0,1001,Ramesh Kumar,Laptop,Electronics,2,45000,2024-01-05,Mumbai,Anil Sharma,2024.0,1.0,January,Friday,90000.0
1,1002,Priya Nair,Mysteeerious product,Electronics,1,15000,2024-01-07,Delhi,Sunita Rao,2024.0,1.0,January,Sunday,15000.0
2,1003,Amit Verma,Keyboard,Accessories,3,1200,2024-01-08,Bangalore,Anil Sharma,2024.0,1.0,January,Monday,3600.0
3,1004,Sunita Patel,Monitor,Electronics,2,22000,2024-01-10,Chennai,Ravi Kumar,2024.0,1.0,January,Wednesday,44000.0
4,1005,Ramesh Kumar,Laptop,Electronics,2,45000,2024-01-05,Mumbai,Anil Sharma,2024.0,1.0,January,Friday,90000.0
5,1006,Kiran Mehta,Mouse,Accessories,10,800,NaT,Pune,Sunita Rao,NaN,NaN,NaN,NaN,8000.0
6,1007,Deepak Singh,Headphones,Electronics,2,3500,2024-01-12,Hyderabad,Ravi Kumar,2024.0,1.0,January,Friday,7000.0
7,1008,Unknown Customer,Webcam,Accessories,1,2500,2024-01-13,Mumbai,Anil Sharma,2024.0,1.0,January,Saturday,2500.0
8,1009,Ananya Das,Laptop,Electronics,1,45000,2024-01-15,Kolkata,Sunita Rao,2024.0,1.0,January,Monday,45000.0
9,1010,Vikram Iyer,Keyboard,Accessories,5,1200,2024-01-15,Chennai,Ravi Kumar,2024.0,1.0,January,Monday,6000.0
10,1011,Pooja Gupta,Monitor,Electronics,2,22000,2024-01-18,Delhi,Anil Sharma,2024.0,1.0,January,Thursday,44000.0
11,1012,Suresh Rao,USB Hub,Accessories,8,600,2024-01-20,Bangalore,Sunita Rao,2024.0,1.0,January,Saturday,4800.0
12,1013,Meera Joshi,Laptop,Electronics,2,45000,2024-01-22,Pune,Ravi Kumar,2024.0,1.0,January,Monday,90000.0
13,1014,Arjun Nair,Headphones,Electronics,3,3500,NaT,Kochi,Anil Sharma,NaN,NaN,NaN,NaN,10500.0
14,1015,Tanvi Mehta,Webcam,Accessories,2,2500,2024-01-25,Surat,Sunita Rao,2024.0,1.0,January,Thursday,5000.0
15,1016,Kiran Mehta,Mouse,Accessories,10,800,2024-01-07,Pune,Sunita Rao,2024.0,1.0,January,Sunday,8000.0
16,1017,Deepak Singh,Keyboard,Accessories,5,1200,2024-01-28,Hyderabad,Ravi Kumar,2024.0,1.0,January,Sunday,6000.0
17,1018,Rohit Verma,Monitor,Electronics,1,22000,2024-01-30,Delhi,Anil Sharma,2024.0,1.0,January,Tuesday,22000.0
18,1019,Sneha Reddy,Laptop,Electronics,1,45000,2024-02-01,Hyderabad,Ravi Kumar,2024.0,2.0,February,Thursday,45000.0
19,1020,Gaurav Shukla,USB Hub,Accessories,15,600,2024-02-03,Lucknow,Sunita Rao,2024.0,2.0,February,Saturday,9000.0
20,1021,Nisha Kapoor,Headphones,Electronics,2,3500,2024-02-05,Chandigarh,Anil Sharma,2024.0,2.0,February,Monday,7000.0
21,1022,Ajay Tiwari,Webcam,Accessories,3,2500,2024-02-07,Bhopal,Ravi Kumar,2024.0,2.0,February,Wednesday,7500.0
22,1023,Ananya Das,Laptop,Electronics,1,45000,2024-01-15,Kolkata,Sunita Rao,2024.0,1.0,January,Monday,45000.0
23,1024,Preeti Saxena,Keyboard,Electronics,4,1200,2024-02-10,Kanpur,Anil Sharma,2024.0,2.0,February,Saturday,4800.0
24,1025,Amit Bose,Mouse,Accessories,6,800,2024-02-12,Kolkata,Sunita Rao,2024.0,2.0,February,Monday,4800.0
25,1026,Unknown Customer,Headphones,Electronics,1,3500,2024-02-14,Mumbai,Ravi Kumar,2024.0,2.0,February,Wednesday,3500.0
26,1027,Rekha Nair,Monitor,Uncategorized,2,22000,2024-02-15,Kochi,Anil Sharma,2024.0,2.0,February,Thursday,44000.0
27,1028,Harish Pillai,Laptop,Electronics,3,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar,2024.0,2.0,February,Sunday,135000.0
28,1029,Sanjay Dubey,USB Hub,Accessories,10,600,2024-02-20,Allahabad,Sunita Rao,2024.0,2.0,February,Tuesday,6000.0
29,1030,Kavya Nambiar,Webcam,Accessories,2,2500,2024-02-22,Thrissur,Anil Sharma,2024.0,2.0,February,Thursday,5000.0

In [75]:
df.dropna(inplace=True)
print(df.isnull().sum().sum())

0